### ISSUE TITLE
Bootcamp 2

### ISSUE THREAD

**Issue by thejameskyle** [thejameskyle/bootcamp#75]
Opening this to hopefully get some input on Bootcamp 2.0.

This version is going to be rewritten from the ground up to take advantage of some of the new features of Sass 3.3

#### Some ideals for 2.0:

- Lighter, cleaner syntax
- Clean up global namespace (functions, mixins, and variables)
- Improve css/grunt output

---

## Proposal

**Here's a quick overview of my current proposal:**

> Warning: None of this has been implemented and will likely change

**Test Suite:**
```scss
@import "functions/positive-number";
@import "bootcamp";
@import "matchers/be-a-positive-number";

@include bootcamp-runner($options: "verbose" "warnings");

@import "tests/positive-number";

@include bootcamp-results;
```

**Create Matchers:**
```scss
@function test-if-its-a-positive-number($number) {
  @return $number > 0;
}

@include bootcamp-register('be a positive number', 'test-if-its-a-positive-number');
```

**Tests:**
```scss
describe("The positive number function") {
  it("should return all positive numbers") {
    @include expect( positive-number( 1 ) to be a positive number );
    @include expect( positive-number( 2 ) to be a positive number );
    @include expect( positive-number( 3 ) to be a positive number );
  }

  it("should return false for zero") {
    @include expect( positive-number( 0 ) to equal false );
  }

  it("should return false for all negative numbers") {
    @include expect( positive-number( -1 ) not to be true );
    @include expect( positive-number( -2 ) not to be true );
    @include expect( positive-number( -3 ) not to be true );
  }
}
```

**Results:**
```css
/* >> Bootcamp >> */

/**
 * Options:
 * - Verbose
 * - Warnings
 */

/**
 * Tests:
 */

/* line 2, ../tests/positive-numbers.scss */
The positive number function should return all positive numbers {
  ✔: expected 1 to be a positive number;
  ✔: expected 2 to be a positive number;
  ✔: expected 3 to be a positive number;
}

/* line 8, ../tests/add-column.scss */
The positive number function should return false for zero {
  ✗: expected 0 to equal false;
}

/* line 12, ../tests/add-column.scss */
The positive number function should return false for all negative numbers {
  ✔: expected false not to be true;
  ✔: expected false not to be true;
  ✔: expected false not to be true;
}

/**
 * Results:
 * ✔ ✔ ✔ ✗ ✔ ✔ ✔
 * 
 *  7 Assertions
 *  3 Tests
 *  2 Passed
 *  1 Failed
 *
 * Suite Failed
 */

/**
 * Warnings:
 * - The "equal" matcher should only be used for numbers, try "be" instead. (1)
 *   - The positive number function should return false for zero: expected 0 to equal false
 */

/* << Bootcamp << */
```

**Grunt:**
```scss
Running "sass:test" (sass) task:

  >> Tip: from terminal you can (command + click) file urls to open them up in your default editor. <<

  Options:
    - Verbose
    - Warnings

  Tests:
    line 2, ../tests/positive-numbers.scss
    The positive number function should return all positive numbers
      ✔ expected 1 to be a positive number
      ✔ expected 2 to be a positive number
      ✔ expected 3 to be a positive number

    line 8, ../tests/positive-numbers.scss
    The positive number function should return false for zero
      ✗ expected 0 to equal false

    line 12, ../tests/positive-numbers.scss
    The positive number function should return false for all negative numbers
      ✔ expected false not to be true
      ✔ expected false not to be true
      ✔ expected false not to be true

  Results:
    ✔ ✔ ✔ ✗ ✔ ✔ ✔

     7 Assertions
     3 Tests
     2 Passed
     1 Failed

    Suite Failed

  Warnings:
    - The "equal" matcher should only be used for numbers, try "be" instead. (1)
      - The positive number function should return false for zero: expected 0 to equal false
```

---

## Breakdown

Going through some of this step by step:

#### Describe/It Blocks

```scss
describe("Function") { /* ... */ }
it("should do something") { /* ... */ }
```

The `describe` and `it` mixins will become functions that return string passed to it, allowing sass's built in nesting to take over.

The change that enables this is getting rid of `xdescribe` and `xit`. I wasn't able to find anyone actually using either, and so they'll be killed off.

The greatest part of this is that it will fix the sass debug comments, so that you'll see the filename and line number of the test. (eg.)

```css
/* line 2, ../tests/positive-numbers.scss */
The positive number function should return all positive numbers {
```

#### Assertions

```scss
@include expect( 1 to equal 1 );
```

> Goodbye parenthesis hell (@HugoGiraudel :wink:)

Here's that syntax broken down:

```scss
expect( [actual value] [to | not to] [matcher] [expected value] )
```

This is going to be powered by some pretty cool logic I've been working on to do a basic fuzzy match on the arguments of `expect` and the registered matchers. Although if some major limitation arises then I will likely go with this syntax:

```scss
@include expect( 1 to "equal" 1 );
```

Here are some other requirements:

```scss
@include expect( 1 to be close to 1, 2 ); // Some matcher take multiple arguments, they will have to be passed in as additional arguments
@include expect( 1 to be positive ); // Some matchers don't take any arguments
```

so `expect` will be defined as:

```scss
@mixin expect($assertion, $args...) { /* ... */ }
```

#### Matcher Creation

```scss
@include bootcamp-register("be something", "be-something-function");
```

I'm really excited about this one. It's the other half of the new assertion syntax. It keeps things out of the global namespace (in the sense that you can name the function anything and still call it in plain language in the assertion).

The function will be called as the following:

```scss
call("be-something-function", $actual [, $expected] [, $args...]);
```

---

## Closing

Let me finish by pointing out how much cleaner this all is

```scss
@import "functions/positive-number"
@import "bootcamp"

$bc-setting-verbose:  false;
$bc-setting-warnings: false;

@include runner-start;

@include describe("The positive number function") {
  @include it("should return all positive numbers") {
    @include should( expect( positive-number( 1 ) ), to( equal( 1 ) ) );
    @include should( expect( positive-number( 2 ) ), to( equal( 2 ) ) );
    @include should( expect( positive-number( 3 ) ), to( equal( 3 ) ) );
  }

  @include it("should return false for zero") {
    @include should( expect( positive-number( 0 ) ), to( equal( false ) ) );
  }

  @include it("should return false for all negative numbers") {
    @include should( expect( positive-number( -1 ) ), not-to( be( true ) ) );
    @include should( expect( positive-number( -2 ) ), not-to( be( true ) ) );
    @include should( expect( positive-number( -3 ) ), not-to( be( true ) ) );
  }
}

@include runner-end;
```

Becomes:

```scss
@import "functions/positive-number"
@import "bootcamp"

@include bootcamp-runner($options: verbose warnings);

describe("The positive number function") {
  it("should return all positive numbers") {
    @include expect( positive-number( 1 ) to equal 1 );
    @include expect( positive-number( 2 ) to equal 2 );
    @include expect( positive-number( 3 ) to equal 3 );
  }

  it("should return false for zero") {
    @include expect( positive-number( 0 ) to equal false );
  }

  it("should return false for all negative numbers") {
    @include expect( positive-number( -1 ) not to be true );
    @include expect( positive-number( -2 ) not to be true );
    @include expect( positive-number( -3 ) not to be true );
  }
}

@include bootcamp-results;
```

aaaahhhh
